-- Vocabulario progress, v1 of the schema.
--
-- The shape here is deliberately inverted from the way the browser stores
-- progress. `reviews` is an append-only log and is the source of truth;
-- `cards` is a fold over it and can be dropped and rebuilt at any time.
--
-- That inversion is the whole point. A new statistic can always be derived
-- from an event log, but history that was never written cannot be recovered.
-- It is what makes changing the scheduling algorithm later a re-fold rather
-- than a reset, and it is what lets two devices merge without a conflict:
-- the log is a set union and the fold is deterministic.

CREATE TABLE IF NOT EXISTS users (
    id            TEXT PRIMARY KEY,           -- 'google:<sub>'
    provider      TEXT NOT NULL,
    provider_id   TEXT NOT NULL,
    display_name  TEXT NOT NULL,
    created_at    INTEGER NOT NULL,
    UNIQUE (provider, provider_id)
);

-- Append-only. Never UPDATEd, never DELETEd.
--
-- `id` is generated by the client, so a retried or duplicated upload collides
-- on the primary key and is ignored rather than double-counted.
--
-- `word_es` is the Spanish string, the same progress key the browser already
-- uses. It is deliberately not a foreign key: the word list lives in a static
-- file, and a words table would have to be re-synced on every deploy. The cost
-- is that renaming a word orphans its rows — but unlike localStorage, here
-- that is repairable with an UPDATE.
CREATE TABLE IF NOT EXISTS reviews (
    id           TEXT PRIMARY KEY,
    user_id      TEXT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    word_es      TEXT NOT NULL,
    deck_id      TEXT,                        -- where the answer happened: context,
    stage        INTEGER,                     -- not identity. A word is one card no
    direction    TEXT,                        -- matter which deck it was met in.
    correct      INTEGER NOT NULL,
    latency_ms   INTEGER,                     -- unused today; the algorithm may want it
    reviewed_at  INTEGER NOT NULL,            -- client clock, ms
    received_at  INTEGER NOT NULL,            -- server clock, ms — catches a skewed device
    source       TEXT NOT NULL DEFAULT 'review',   -- 'review' | 'import'
    srs_version  INTEGER NOT NULL
);

-- The fold reads one word's whole history in order; the sync response reads
-- everything since a timestamp.
CREATE INDEX IF NOT EXISTS idx_reviews_fold   ON reviews (user_id, word_es, reviewed_at);
CREATE INDEX IF NOT EXISTS idx_reviews_recent ON reviews (user_id, reviewed_at DESC);

-- Derived from `reviews`. Kept only so the first load after sign-in is one
-- indexed read instead of a fold over everything.
CREATE TABLE IF NOT EXISTS cards (
    user_id      TEXT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    word_es      TEXT NOT NULL,
    box          INTEGER NOT NULL,
    due_at       INTEGER NOT NULL,            -- a timestamp, not a question counter
    seen         INTEGER NOT NULL,
    correct      INTEGER NOT NULL,
    last_seen_at INTEGER NOT NULL,
    srs_version  INTEGER NOT NULL,
    updated_at   INTEGER NOT NULL,
    PRIMARY KEY (user_id, word_es)
);

CREATE INDEX IF NOT EXISTS idx_cards_due     ON cards (user_id, due_at);
CREATE INDEX IF NOT EXISTS idx_cards_changed ON cards (user_id, updated_at);

-- A round is a UI concept and can be abandoned half-finished, so it does not
-- belong in `reviews`. Personal history only — nothing here ranks one learner
-- against another.
CREATE TABLE IF NOT EXISTS rounds (
    id          TEXT PRIMARY KEY,
    user_id     TEXT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    deck_id     TEXT NOT NULL,
    stage       INTEGER NOT NULL,
    direction   TEXT NOT NULL,
    asked       INTEGER NOT NULL,
    correct     INTEGER NOT NULL,
    score       INTEGER NOT NULL,
    best_streak INTEGER NOT NULL,
    started_at  INTEGER NOT NULL,
    ended_at    INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_rounds_user ON rounds (user_id, ended_at DESC);

-- The handful of per-user scalars that are not per-word.
CREATE TABLE IF NOT EXISTS profiles (
    user_id     TEXT PRIMARY KEY REFERENCES users (id) ON DELETE CASCADE,
    best_score  INTEGER NOT NULL DEFAULT 0,
    best_streak INTEGER NOT NULL DEFAULT 0,
    synced_at   INTEGER NOT NULL DEFAULT 0
);
