// Word decks. Nouns carry their article so gender is learned with the word.
//
// Each deck has three stages of increasing difficulty. Stage 1 of every original
// deck is the 120-word set the app shipped with — the Spanish text is the
// progress key, so those cards keep their history from before stages existed.
// Never rewrite an `es` string that has shipped: it silently orphans progress.
//
// Vocabulary is Latin American Spanish with US English glosses. One shipped key
// was rewritten to get there — 'el billete' -> 'el boleto' — which reset that
// single word for anyone who had already played it. It was done while the app
// had effectively no users; a rename after this point needs a real migration.

export const STAGE_NAMES = ['Basics', 'Everyday', 'Fluent'];
export const STAGE_COUNT = STAGE_NAMES.length;
export const ALL_DECK_ID = 'todos';

export const DECKS = [
  {
    id: 'comida',
    name: 'Food',
    emoji: '🍎',
    stages: [
      [
        { es: 'la manzana', en: 'apple' },
        { es: 'el pan', en: 'bread' },
        { es: 'el queso', en: 'cheese' },
        { es: 'la leche', en: 'milk' },
        { es: 'el huevo', en: 'egg' },
        { es: 'el pollo', en: 'chicken' },
        { es: 'el arroz', en: 'rice' },
        { es: 'la fresa', en: 'strawberry', alt: [{ es: 'la frutilla', region: 'Southern Cone' }] },
        { es: 'la naranja', en: 'orange' },
        { es: 'el pescado', en: 'fish' },
        { es: 'la sal', en: 'salt' },
        { es: 'el azúcar', en: 'sugar' },
        { es: 'la cebolla', en: 'onion' },
        { es: 'el ajo', en: 'garlic' },
        { es: 'la sandía', en: 'watermelon' },
        { es: 'el plátano', en: 'banana' },
        { es: 'la uva', en: 'grape' },
        { es: 'el tomate', en: 'tomato' },
        { es: 'la papa', en: 'potato' },
        { es: 'la zanahoria', en: 'carrot' },
        { es: 'el frijol', en: 'bean' },
        { es: 'el maíz', en: 'corn' },
        { es: 'la mantequilla', en: 'butter' },
        { es: 'el aceite', en: 'oil' },
        { es: 'la pimienta', en: 'pepper' },
        { es: 'el agua', en: 'water' },
        { es: 'el café', en: 'coffee' },
        { es: 'el té', en: 'tea' },
        { es: 'el yogur', en: 'yogurt' },
        { es: 'la nuez', en: 'walnut' }
      ],
      [
        { es: 'la carne', en: 'meat' },
        { es: 'la sopa', en: 'soup' },
        { es: 'la ensalada', en: 'salad' },
        { es: 'el postre', en: 'dessert' },
        { es: 'el jamón', en: 'ham' },
        { es: 'la galleta', en: 'cookie' },
        { es: 'el helado', en: 'ice cream' },
        { es: 'el limón', en: 'lemon' },
        { es: 'la pera', en: 'pear' },
        { es: 'el pastel', en: 'cake', alt: [{ es: 'la torta', region: 'much of Latin America' }] },
        { es: 'la harina', en: 'flour' },
        { es: 'el tocino', en: 'bacon' },
        { es: 'la salchicha', en: 'sausage' },
        { es: 'el camarón', en: 'shrimp' },
        { es: 'el atún', en: 'tuna' },
        { es: 'la miel', en: 'honey' },
        { es: 'el jugo', en: 'juice' },
        { es: 'la bebida', en: 'beverage' },
        { es: 'el sabor', en: 'flavor' },
        { es: 'la pasta', en: 'pasta' },
        { es: 'el pavo', en: 'turkey' },
        { es: 'la mostaza', en: 'mustard' },
        { es: 'la salsa', en: 'sauce' },
        { es: 'el vinagre', en: 'vinegar' },
        { es: 'la mermelada', en: 'jam' },
        { es: 'el cereal', en: 'cereal' },
        { es: 'la tostada', en: 'toast' },
        { es: 'el sándwich', en: 'sandwich' },
        { es: 'el bocadillo', en: 'snack' },
        { es: 'la merienda', en: 'afternoon snack' }
      ],
      [
        { es: 'el aguacate', en: 'avocado', alt: [{ es: 'la palta', region: 'Andes & Southern Cone' }] },
        { es: 'la lechuga', en: 'lettuce' },
        { es: 'el pepino', en: 'cucumber' },
        { es: 'la calabaza', en: 'pumpkin' },
        { es: 'el champiñón', en: 'mushroom' },
        { es: 'el desayuno', en: 'breakfast' },
        { es: 'el almuerzo', en: 'lunch' },
        { es: 'la cena', en: 'dinner' },
        { es: 'la receta', en: 'recipe' },
        { es: 'la ternera', en: 'veal' },
        { es: 'el trigo', en: 'wheat' },
        { es: 'el aderezo', en: 'dressing' },
        { es: 'el condimento', en: 'seasoning' },
        { es: 'la especia', en: 'spice' },
        { es: 'el guiso', en: 'stew' },
        { es: 'el caldo', en: 'broth' },
        { es: 'la masa', en: 'dough' },
        { es: 'la corteza del pan', en: 'crust' },
        { es: 'el relleno', en: 'filling' },
        { es: 'la rebanada', en: 'slice' },
        { es: 'la porción', en: 'portion' },
        { es: 'el sartén', en: 'frying pan' },
        { es: 'la olla', en: 'pot' },
        { es: 'el horno de leña', en: 'wood oven' },
        { es: 'hervir', en: 'to boil' },
        { es: 'freír', en: 'to fry' },
        { es: 'el escabeche', en: 'pickling' },
        { es: 'la levadura', en: 'yeast' },
        { es: 'el puré', en: 'purée' },
        { es: 'la guarnición', en: 'side dish' }
      ]
    ]
  },
  {
    id: 'animales',
    name: 'Animals',
    emoji: '🦊',
    stages: [
      [
        { es: 'el perro', en: 'dog' },
        { es: 'el gato', en: 'cat' },
        { es: 'el caballo', en: 'horse' },
        { es: 'el pájaro', en: 'bird' },
        { es: 'la vaca', en: 'cow' },
        { es: 'el cerdo', en: 'pig', alt: [{ es: 'el chancho', region: 'much of Latin America' }, { es: 'el puerco', region: 'Mexico' }] },
        { es: 'la oveja', en: 'sheep' },
        { es: 'el conejo', en: 'rabbit' },
        { es: 'el ratón', en: 'mouse' },
        { es: 'la araña', en: 'spider' },
        { es: 'el oso', en: 'bear' },
        { es: 'el zorro', en: 'fox' },
        { es: 'la tortuga', en: 'turtle' },
        { es: 'la ballena', en: 'whale' },
        { es: 'el murciélago', en: 'bat' },
        { es: 'la gallina', en: 'hen' },
        { es: 'el pato', en: 'duck' },
        { es: 'el ratón de campo', en: 'field mouse' },
        { es: 'la abeja', en: 'bee' },
        { es: 'la mariposa', en: 'butterfly' },
        { es: 'la hormiga', en: 'ant' },
        { es: 'la mosca', en: 'fly' },
        { es: 'la cucaracha', en: 'cockroach' },
        { es: 'el grillo', en: 'cricket' },
        { es: 'la paloma', en: 'pigeon' },
        { es: 'el pollito', en: 'chick' },
        { es: 'el ternero', en: 'calf' },
        { es: 'el cachorro', en: 'puppy' },
        { es: 'el gatito', en: 'kitten' },
        { es: 'la mula', en: 'mule' }
      ],
      [
        { es: 'el león', en: 'lion' },
        { es: 'el tigre', en: 'tiger' },
        { es: 'el elefante', en: 'elephant' },
        { es: 'el mono', en: 'monkey' },
        { es: 'la serpiente', en: 'snake' },
        { es: 'el burro', en: 'donkey' },
        { es: 'la rana', en: 'frog' },
        { es: 'el lobo', en: 'wolf' },
        { es: 'la cabra', en: 'goat' },
        { es: 'el gallo', en: 'rooster' },
        { es: 'la jirafa', en: 'giraffe' },
        { es: 'la ardilla', en: 'squirrel' },
        { es: 'el cocodrilo', en: 'crocodile' },
        { es: 'el delfín', en: 'dolphin' },
        { es: 'el tiburón', en: 'shark' },
        { es: 'el rinoceronte', en: 'rhinoceros' },
        { es: 'el hipopótamo', en: 'hippopotamus' },
        { es: 'la cebra', en: 'zebra' },
        { es: 'el canguro', en: 'kangaroo' },
        { es: 'el koala', en: 'koala' },
        { es: 'el panda', en: 'panda' },
        { es: 'el leopardo', en: 'leopard' },
        { es: 'la pantera', en: 'panther' },
        { es: 'el chimpancé', en: 'chimpanzee' },
        { es: 'el gorila', en: 'gorilla' },
        { es: 'la llama', en: 'llama' },
        { es: 'la alpaca', en: 'alpaca' },
        { es: 'el jaguar', en: 'jaguar' },
        { es: 'el puma', en: 'puma' },
        { es: 'el venado', en: 'deer' }
      ],
      [
        { es: 'el camello', en: 'camel' },
        { es: 'el águila', en: 'eagle' },
        { es: 'el búho', en: 'owl' },
        { es: 'el escarabajo', en: 'beetle' },
        { es: 'el erizo', en: 'hedgehog' },
        { es: 'la foca', en: 'seal' },
        { es: 'el pingüino', en: 'penguin' },
        { es: 'el caracol', en: 'snail' },
        { es: 'la garra', en: 'claw' },
        { es: 'el ganso', en: 'goose' },
        { es: 'el cisne', en: 'swan' },
        { es: 'el halcón', en: 'falcon' },
        { es: 'el pulpo', en: 'octopus' },
        { es: 'el calamar', en: 'squid' },
        { es: 'la medusa', en: 'jellyfish' },
        { es: 'el cangrejo', en: 'crab' },
        { es: 'la langosta', en: 'lobster' },
        { es: 'la almeja', en: 'clam' },
        { es: 'el mejillón', en: 'mussel' },
        { es: 'la trucha', en: 'trout' },
        { es: 'el salmón', en: 'salmon' },
        { es: 'la anguila', en: 'eel' },
        { es: 'el lagarto', en: 'lizard' },
        { es: 'el camaleón', en: 'chameleon' },
        { es: 'la iguana', en: 'iguana' },
        { es: 'el sapo', en: 'toad' },
        { es: 'la libélula', en: 'dragonfly' },
        { es: 'la avispa', en: 'wasp' },
        { es: 'la polilla', en: 'moth' },
        { es: 'el gusano', en: 'worm' }
      ]
    ]
  },
  {
    id: 'casa',
    name: 'The Home',
    emoji: '🏠',
    stages: [
      [
        { es: 'la casa', en: 'house' },
        { es: 'la puerta', en: 'door' },
        { es: 'la ventana', en: 'window' },
        { es: 'la cocina', en: 'kitchen' },
        { es: 'el baño', en: 'bathroom' },
        { es: 'la cama', en: 'bed' },
        { es: 'la silla', en: 'chair' },
        { es: 'la mesa', en: 'table' },
        { es: 'el techo', en: 'roof' },
        { es: 'la llave', en: 'key' },
        { es: 'el espejo', en: 'mirror' },
        { es: 'la escalera', en: 'stairs' },
        { es: 'el jardín', en: 'garden' },
        { es: 'la almohada', en: 'pillow' },
        { es: 'el cajón', en: 'drawer' },
        { es: 'el cuarto', en: 'bedroom' },
        { es: 'la sala', en: 'living room' },
        { es: 'el comedor', en: 'dining room' },
        { es: 'el garaje', en: 'garage' },
        { es: 'el patio', en: 'patio' },
        { es: 'el balcón', en: 'balcony' },
        { es: 'el mueble', en: 'piece of furniture' },
        { es: 'el reloj de pared', en: 'wall clock' },
        { es: 'la maceta', en: 'flowerpot' },
        { es: 'el cuadro', en: 'framed picture' },
        { es: 'la sábana', en: 'bedsheet' },
        { es: 'el colchón', en: 'mattress' },
        { es: 'la ducha caliente', en: 'hot shower' },
        { es: 'el lavabo', en: 'bathroom sink' },
        { es: 'el inodoro', en: 'toilet' }
      ],
      [
        { es: 'el suelo', en: 'floor' },
        { es: 'la pared', en: 'wall' },
        { es: 'el sofá', en: 'sofa' },
        { es: 'la lámpara', en: 'lamp' },
        { es: 'el refrigerador', en: 'fridge', alt: [{ es: 'la nevera', region: 'Spain' }, { es: 'la heladera', region: 'Argentina' }] },
        { es: 'el horno', en: 'oven' },
        { es: 'el plato', en: 'plate' },
        { es: 'el vaso', en: 'drinking glass' },
        { es: 'la taza', en: 'cup' },
        { es: 'el cuchillo', en: 'knife' },
        { es: 'el tenedor', en: 'fork' },
        { es: 'la cuchara', en: 'spoon' },
        { es: 'la toalla', en: 'towel' },
        { es: 'el jabón', en: 'soap' },
        { es: 'la manta', en: 'blanket', alt: [{ es: 'la cobija', region: 'Mexico' }, { es: 'la frazada', region: 'South America' }] },
        { es: 'la olla a presión', en: 'pressure cooker' },
        { es: 'la licuadora', en: 'blender' },
        { es: 'la cafetera', en: 'coffee maker' },
        { es: 'el microondas', en: 'microwave' },
        { es: 'la lavadora', en: 'washing machine' },
        { es: 'la secadora', en: 'clothes dryer' },
        { es: 'el ventilador', en: 'fan' },
        { es: 'la calefacción', en: 'heating' },
        { es: 'el aire acondicionado', en: 'air conditioning' },
        { es: 'la servilleta', en: 'napkin' },
        { es: 'el mantel', en: 'tablecloth' },
        { es: 'la bandeja', en: 'tray' },
        { es: 'el tazón', en: 'bowl' },
        { es: 'la jarra', en: 'pitcher' },
        { es: 'el abrelatas', en: 'can opener' }
      ],
      [
        { es: 'el pasillo', en: 'hallway' },
        { es: 'el sótano', en: 'basement' },
        { es: 'el desván', en: 'attic' },
        { es: 'la chimenea', en: 'fireplace' },
        { es: 'el enchufe', en: 'plug' },
        { es: 'la bombilla', en: 'light bulb' },
        { es: 'el grifo', en: 'faucet', alt: [{ es: 'la llave', region: 'Mexico' }, { es: 'la canilla', region: 'Argentina' }] },
        { es: 'el fregadero', en: 'sink' },
        { es: 'la cortina', en: 'curtain' },
        { es: 'la alfombra', en: 'rug' },
        { es: 'el armario', en: 'closet', alt: [{ es: 'el clóset', region: 'Latin America' }] },
        { es: 'el estante', en: 'shelf' },
        { es: 'la basura', en: 'trash' },
        { es: 'la cerradura', en: 'lock' },
        { es: 'el timbre', en: 'doorbell' },
        { es: 'el zaguán', en: 'entryway' },
        { es: 'el altillo', en: 'loft' },
        { es: 'la buhardilla', en: 'garret' },
        { es: 'el tragaluz', en: 'skylight' },
        { es: 'la viga', en: 'beam' },
        { es: 'el marco', en: 'frame' },
        { es: 'el umbral', en: 'threshold' },
        { es: 'la bisagra', en: 'hinge' },
        { es: 'el pomo', en: 'doorknob' },
        { es: 'la persiana', en: 'blind' },
        { es: 'el zócalo', en: 'baseboard' },
        { es: 'la moldura', en: 'molding' },
        { es: 'el revestimiento', en: 'cladding' },
        { es: 'la tubería', en: 'plumbing' },
        { es: 'el desagüe', en: 'drain' }
      ]
    ]
  },
  {
    id: 'verbos',
    name: 'Verbs',
    emoji: '🏃',
    stages: [
      [
        { es: 'hablar', en: 'to speak' },
        { es: 'comer', en: 'to eat' },
        { es: 'beber', en: 'to drink' },
        { es: 'vivir', en: 'to live' },
        { es: 'correr', en: 'to run' },
        { es: 'dormir', en: 'to sleep' },
        { es: 'escribir', en: 'to write' },
        { es: 'leer', en: 'to read' },
        { es: 'comprar', en: 'to buy' },
        { es: 'trabajar', en: 'to work' },
        { es: 'salir', en: 'to leave' },
        { es: 'venir', en: 'to come' },
        { es: 'pensar', en: 'to think' },
        { es: 'entender', en: 'to understand' },
        { es: 'olvidar', en: 'to forget' },
        { es: 'ser', en: 'to be' },
        { es: 'estar', en: 'to be located' },
        { es: 'tener', en: 'to have' },
        { es: 'hacer', en: 'to do' },
        { es: 'ir', en: 'to go' },
        { es: 'poder', en: 'to be able to' },
        { es: 'querer', en: 'to want' },
        { es: 'saber', en: 'to know a fact' },
        { es: 'conocer', en: 'to be acquainted with' },
        { es: 'dar', en: 'to give' },
        { es: 'ver', en: 'to see' },
        { es: 'poner', en: 'to put' },
        { es: 'decir', en: 'to say' },
        { es: 'sentir', en: 'to feel' },
        { es: 'vender', en: 'to sell' }
      ],
      [
        { es: 'abrir', en: 'to open' },
        { es: 'cerrar', en: 'to close' },
        { es: 'empezar', en: 'to begin' },
        { es: 'terminar', en: 'to finish' },
        { es: 'llegar', en: 'to arrive' },
        { es: 'llevar', en: 'to carry' },
        { es: 'traer', en: 'to bring' },
        { es: 'pedir', en: 'to ask for' },
        { es: 'responder', en: 'to answer' },
        { es: 'buscar', en: 'to look for' },
        { es: 'encontrar', en: 'to find' },
        { es: 'perder', en: 'to lose' },
        { es: 'ganar', en: 'to win' },
        { es: 'jugar', en: 'to play' },
        { es: 'cantar', en: 'to sing' },
        { es: 'recordar', en: 'to remember' },
        { es: 'aprender', en: 'to learn' },
        { es: 'enseñar', en: 'to teach' },
        { es: 'escuchar', en: 'to listen' },
        { es: 'mirar', en: 'to watch' },
        { es: 'esperar', en: 'to wait' },
        { es: 'ayudar', en: 'to help' },
        { es: 'necesitar', en: 'to need' },
        { es: 'usar', en: 'to use' },
        { es: 'cambiar', en: 'to change' },
        { es: 'empujar', en: 'to push' },
        { es: 'tirar', en: 'to pull' },
        { es: 'tocar', en: 'to touch' },
        { es: 'caminar', en: 'to walk' },
        { es: 'viajar', en: 'to travel' }
      ],
      [
        { es: 'construir', en: 'to build' },
        { es: 'romper', en: 'to break' },
        { es: 'crecer', en: 'to grow' },
        { es: 'elegir', en: 'to choose' },
        { es: 'prometer', en: 'to promise' },
        { es: 'mentir', en: 'to tell a lie' },
        { es: 'soñar', en: 'to dream' },
        { es: 'reír', en: 'to laugh' },
        { es: 'llorar', en: 'to cry' },
        { es: 'conseguir', en: 'to obtain' },
        { es: 'devolver', en: 'to give back' },
        { es: 'apagar', en: 'to turn off' },
        { es: 'encender', en: 'to turn on' },
        { es: 'avisar', en: 'to warn' },
        { es: 'lograr', en: 'to achieve' },
        { es: 'atreverse', en: 'to dare' },
        { es: 'arrepentirse', en: 'to regret' },
        { es: 'agradecer', en: 'to be grateful' },
        { es: 'merecer', en: 'to deserve' },
        { es: 'pertenecer', en: 'to belong' },
        { es: 'surgir', en: 'to arise' },
        { es: 'desarrollar', en: 'to develop' },
        { es: 'aportar', en: 'to contribute' },
        { es: 'reconocer', en: 'to recognize' },
        { es: 'advertir', en: 'to caution' },
        { es: 'sugerir', en: 'to suggest' },
        { es: 'exigir', en: 'to demand' },
        { es: 'impedir', en: 'to prevent from' },
        { es: 'resolver', en: 'to solve' },
        { es: 'suponer', en: 'to assume' }
      ]
    ]
  },
  {
    id: 'viajes',
    name: 'Travel',
    emoji: '✈️',
    stages: [
      [
        { es: 'el aeropuerto', en: 'airport' },
        { es: 'el tren', en: 'train' },
        { es: 'el boleto', en: 'ticket', alt: [{ es: 'el billete', region: 'Spain' }] },
        { es: 'la maleta', en: 'suitcase' },
        { es: 'el mapa', en: 'map' },
        { es: 'la playa', en: 'beach' },
        { es: 'el hotel', en: 'hotel' },
        { es: 'la calle', en: 'street' },
        { es: 'el puente', en: 'bridge' },
        { es: 'la ciudad', en: 'city' },
        { es: 'el pueblo', en: 'village' },
        { es: 'el viaje', en: 'trip' },
        { es: 'la frontera', en: 'border' },
        { es: 'el equipaje', en: 'luggage' },
        { es: 'la carretera', en: 'highway' }
      ],
      [
        { es: 'el avión', en: 'airplane' },
        { es: 'el barco', en: 'ship' },
        { es: 'el carro', en: 'car', alt: [{ es: 'el coche', region: 'Spain' }, { es: 'el auto', region: 'Southern Cone' }] },
        { es: 'el autobús', en: 'bus', alt: [{ es: 'el camión', region: 'Mexico' }, { es: 'la guagua', region: 'Caribbean' }, { es: 'el colectivo', region: 'Argentina' }] },
        { es: 'la estación', en: 'station' },
        { es: 'el pasaporte', en: 'passport' },
        { es: 'la aduana', en: 'customs' },
        { es: 'el vuelo', en: 'flight' },
        { es: 'la llegada', en: 'arrival' },
        { es: 'la salida', en: 'departure' },
        { es: 'el asiento', en: 'seat' },
        { es: 'la reserva', en: 'booking' },
        { es: 'el destino', en: 'destination' },
        { es: 'la isla', en: 'island' },
        { es: 'el sendero', en: 'trail' }
      ],
      [
        { es: 'el crucero', en: 'cruise' },
        { es: 'la brújula', en: 'compass' },
        { es: 'el itinerario', en: 'itinerary' },
        { es: 'la escala', en: 'layover' },
        { es: 'el andén', en: 'platform' },
        { es: 'el peaje', en: 'toll' },
        { es: 'la mochila', en: 'backpack' },
        { es: 'el albergue', en: 'hostel' },
        { es: 'la aventura', en: 'adventure' },
        { es: 'el paisaje', en: 'landscape' },
        { es: 'la cumbre', en: 'summit' },
        { es: 'el desvío', en: 'detour' },
        { es: 'la travesía', en: 'crossing' },
        { es: 'el guía', en: 'tour guide' },
        { es: 'el retraso', en: 'delay' }
      ]
    ]
  },
  {
    id: 'cuerpo',
    name: 'The Body',
    emoji: '🖐️',
    stages: [
      [
        { es: 'la cabeza', en: 'head' },
        { es: 'la mano', en: 'hand' },
        { es: 'el pie', en: 'foot' },
        { es: 'el ojo', en: 'eye' },
        { es: 'la boca', en: 'mouth' },
        { es: 'la nariz', en: 'nose' },
        { es: 'la oreja', en: 'ear' },
        { es: 'el brazo', en: 'arm' },
        { es: 'la pierna', en: 'leg' },
        { es: 'el corazón', en: 'heart' },
        { es: 'el dedo', en: 'finger' },
        { es: 'la espalda', en: 'back' },
        { es: 'el hombro', en: 'shoulder' },
        { es: 'la rodilla', en: 'knee' },
        { es: 'el pelo', en: 'hair' }
      ],
      [
        { es: 'la cara', en: 'face' },
        { es: 'el cuello', en: 'neck' },
        { es: 'el diente', en: 'tooth' },
        { es: 'la lengua', en: 'tongue' },
        { es: 'el labio', en: 'lip' },
        { es: 'la ceja', en: 'eyebrow' },
        { es: 'el codo', en: 'elbow' },
        { es: 'la muñeca', en: 'wrist' },
        { es: 'el tobillo', en: 'ankle' },
        { es: 'la uña', en: 'fingernail' },
        { es: 'el pecho', en: 'chest' },
        { es: 'el estómago', en: 'stomach' },
        { es: 'la piel', en: 'skin' },
        { es: 'el hueso', en: 'bone' },
        { es: 'la sangre', en: 'blood' }
      ],
      [
        { es: 'el cerebro', en: 'brain' },
        { es: 'el pulmón', en: 'lung' },
        { es: 'el hígado', en: 'liver' },
        { es: 'el riñón', en: 'kidney' },
        { es: 'la costilla', en: 'rib' },
        { es: 'el músculo', en: 'muscle' },
        { es: 'la vena', en: 'vein' },
        { es: 'el nervio', en: 'nerve' },
        { es: 'la garganta', en: 'throat' },
        { es: 'la cadera', en: 'hip' },
        { es: 'la barbilla', en: 'chin' },
        { es: 'la mejilla', en: 'cheek' },
        { es: 'la pestaña', en: 'eyelash' },
        { es: 'el párpado', en: 'eyelid' },
        { es: 'el talón', en: 'heel' }
      ]
    ]
  },
  {
    id: 'tiempo',
    name: 'Days & Weather',
    emoji: '🗓️',
    stages: [
      [
        { es: 'el lunes', en: 'Monday' },
        { es: 'el martes', en: 'Tuesday' },
        { es: 'el miércoles', en: 'Wednesday' },
        { es: 'el jueves', en: 'Thursday' },
        { es: 'el viernes', en: 'Friday' },
        { es: 'el sábado', en: 'Saturday' },
        { es: 'el domingo', en: 'Sunday' },
        { es: 'hoy', en: 'today' },
        { es: 'mañana', en: 'tomorrow' },
        { es: 'ayer', en: 'yesterday' },
        { es: 'la semana', en: 'week' },
        { es: 'el mes', en: 'month' },
        { es: 'el año', en: 'year' },
        { es: 'la lluvia', en: 'rain' },
        { es: 'la nieve', en: 'snow' }
      ],
      [
        { es: 'el sol', en: 'sun' },
        { es: 'la luna', en: 'moon' },
        { es: 'la nube', en: 'cloud' },
        { es: 'el viento', en: 'wind' },
        { es: 'la tormenta', en: 'storm' },
        { es: 'el cielo', en: 'sky' },
        { es: 'la niebla', en: 'fog' },
        { es: 'el hielo', en: 'ice' },
        { es: 'el calor', en: 'heat' },
        { es: 'la primavera', en: 'spring' },
        { es: 'el verano', en: 'summer' },
        { es: 'el otoño', en: 'fall' },
        { es: 'el invierno', en: 'winter' },
        { es: 'la hora', en: 'hour' },
        { es: 'el minuto', en: 'minute' }
      ],
      [
        { es: 'el amanecer', en: 'dawn' },
        { es: 'el atardecer', en: 'dusk' },
        { es: 'la medianoche', en: 'midnight' },
        { es: 'el mediodía', en: 'noon' },
        { es: 'el relámpago', en: 'lightning' },
        { es: 'el trueno', en: 'thunder' },
        { es: 'el granizo', en: 'hail' },
        { es: 'la sequía', en: 'drought' },
        { es: 'la inundación', en: 'flood' },
        { es: 'el arcoíris', en: 'rainbow' },
        { es: 'la brisa', en: 'breeze' },
        { es: 'la humedad', en: 'humidity' },
        { es: 'el pronóstico', en: 'forecast' },
        { es: 'el siglo', en: 'century' },
        { es: 'la década', en: 'decade' }
      ]
    ]
  },
  {
    id: 'adjetivos',
    name: 'Adjectives',
    emoji: '🎨',
    stages: [
      [
        { es: 'grande', en: 'big' },
        { es: 'pequeño', en: 'small' },
        { es: 'rápido', en: 'fast' },
        { es: 'lento', en: 'slow' },
        { es: 'feliz', en: 'happy' },
        { es: 'triste', en: 'sad' },
        { es: 'caro', en: 'expensive' },
        { es: 'barato', en: 'cheap' },
        { es: 'fuerte', en: 'strong' },
        { es: 'débil', en: 'weak' },
        { es: 'limpio', en: 'clean' },
        { es: 'sucio', en: 'dirty' },
        { es: 'caliente', en: 'hot' },
        { es: 'frío', en: 'cold' },
        { es: 'nuevo', en: 'new' }
      ],
      [
        { es: 'alto', en: 'tall' },
        { es: 'bajo', en: 'short' },
        { es: 'largo', en: 'long' },
        { es: 'corto', en: 'brief' },
        { es: 'joven', en: 'young' },
        { es: 'viejo', en: 'old' },
        { es: 'rico', en: 'rich' },
        { es: 'pobre', en: 'poor' },
        { es: 'fácil', en: 'easy' },
        { es: 'difícil', en: 'difficult' },
        { es: 'lleno', en: 'full' },
        { es: 'vacío', en: 'empty' },
        { es: 'claro', en: 'clear' },
        { es: 'oscuro', en: 'dark' },
        { es: 'bonito', en: 'pretty' }
      ],
      [
        { es: 'amable', en: 'kind' },
        { es: 'grosero', en: 'rude' },
        { es: 'valiente', en: 'brave' },
        { es: 'cobarde', en: 'cowardly' },
        { es: 'orgulloso', en: 'proud' },
        { es: 'humilde', en: 'humble' },
        { es: 'tranquilo', en: 'calm' },
        { es: 'ruidoso', en: 'noisy' },
        { es: 'profundo', en: 'deep' },
        { es: 'estrecho', en: 'narrow' },
        { es: 'ancho', en: 'wide' },
        { es: 'suave', en: 'soft' },
        { es: 'áspero', en: 'rough' },
        { es: 'brillante', en: 'bright' },
        { es: 'borroso', en: 'blurry' }
      ]
    ]
  },
  {
    id: 'familia',
    name: 'Family & People',
    emoji: '👪',
    stages: [
      [
        { es: 'la madre', en: 'mother' },
        { es: 'el padre', en: 'father' },
        { es: 'el hermano', en: 'brother' },
        { es: 'la hermana', en: 'sister' },
        { es: 'el hijo', en: 'son' },
        { es: 'la hija', en: 'daughter' },
        { es: 'el abuelo', en: 'grandfather' },
        { es: 'la abuela', en: 'grandmother' },
        { es: 'el amigo', en: 'friend' },
        { es: 'el niño', en: 'boy' },
        { es: 'la niña', en: 'girl' },
        { es: 'el hombre', en: 'man' },
        { es: 'la mujer', en: 'woman' },
        { es: 'el bebé', en: 'baby' },
        { es: 'la familia', en: 'family' }
      ],
      [
        { es: 'el tío', en: 'uncle' },
        { es: 'la tía', en: 'aunt' },
        { es: 'el primo', en: 'cousin' },
        { es: 'el sobrino', en: 'nephew' },
        { es: 'la sobrina', en: 'niece' },
        { es: 'el esposo', en: 'husband' },
        { es: 'la esposa', en: 'wife' },
        { es: 'el vecino', en: 'neighbor' },
        { es: 'el novio', en: 'boyfriend' },
        { es: 'la novia', en: 'girlfriend' },
        { es: 'el nieto', en: 'grandson' },
        { es: 'la nieta', en: 'granddaughter' },
        { es: 'el suegro', en: 'father-in-law' },
        { es: 'el cuñado', en: 'brother-in-law' },
        { es: 'el gemelo', en: 'twin' }
      ],
      [
        { es: 'el antepasado', en: 'ancestor' },
        { es: 'el pariente', en: 'relative' },
        { es: 'la pareja', en: 'partner' },
        { es: 'el huérfano', en: 'orphan' },
        { es: 'la viuda', en: 'widow' },
        { es: 'el padrino', en: 'godfather' },
        { es: 'la madrina', en: 'godmother' },
        { es: 'el yerno', en: 'son-in-law' },
        { es: 'la nuera', en: 'daughter-in-law' },
        { es: 'el compañero', en: 'companion' },
        { es: 'el desconocido', en: 'stranger' },
        { es: 'el invitado', en: 'guest' },
        { es: 'el anfitrión', en: 'host' },
        { es: 'la generación', en: 'generation' },
        { es: 'el apellido', en: 'surname' }
      ]
    ]
  },
  {
    id: 'numeros',
    name: 'Numbers & Money',
    emoji: '🔢',
    stages: [
      [
        { es: 'uno', en: 'one' },
        { es: 'dos', en: 'two' },
        { es: 'tres', en: 'three' },
        { es: 'cuatro', en: 'four' },
        { es: 'cinco', en: 'five' },
        { es: 'seis', en: 'six' },
        { es: 'siete', en: 'seven' },
        { es: 'ocho', en: 'eight' },
        { es: 'nueve', en: 'nine' },
        { es: 'diez', en: 'ten' },
        { es: 'el dinero', en: 'money' },
        { es: 'el precio', en: 'price' },
        { es: 'primero', en: 'first' },
        { es: 'último', en: 'last' },
        { es: 'medio', en: 'half' }
      ],
      [
        { es: 'veinte', en: 'twenty' },
        { es: 'treinta', en: 'thirty' },
        { es: 'cuarenta', en: 'forty' },
        { es: 'cincuenta', en: 'fifty' },
        { es: 'cien', en: 'a hundred' },
        { es: 'mil', en: 'a thousand' },
        { es: 'el número', en: 'number' },
        { es: 'la cuenta', en: 'bill' },
        { es: 'la moneda', en: 'coin' },
        { es: 'el efectivo', en: 'cash' },
        { es: 'la tarjeta', en: 'card' },
        { es: 'el descuento', en: 'discount' },
        { es: 'la propina', en: 'tip' },
        { es: 'el cambio', en: 'change' },
        { es: 'gratis', en: 'free of charge' }
      ],
      [
        { es: 'el tercio', en: 'a third' },
        { es: 'el porcentaje', en: 'percentage' },
        { es: 'la suma', en: 'sum' },
        { es: 'la resta', en: 'subtraction' },
        { es: 'el impuesto', en: 'tax' },
        { es: 'el préstamo', en: 'loan' },
        { es: 'la deuda', en: 'debt' },
        { es: 'el ahorro', en: 'savings' },
        { es: 'la ganancia', en: 'profit' },
        { es: 'la pérdida', en: 'loss' },
        { es: 'el presupuesto', en: 'budget' },
        { es: 'la factura', en: 'invoice' },
        { es: 'la inversión', en: 'investment' },
        { es: 'el sueldo', en: 'salary' },
        { es: 'la riqueza', en: 'wealth' }
      ]
    ]
  },
  {
    id: 'trabajo',
    name: 'Work & School',
    emoji: '🎓',
    stages: [
      [
        { es: 'la escuela', en: 'school' },
        { es: 'el libro', en: 'book' },
        { es: 'el papel', en: 'paper' },
        { es: 'el lápiz', en: 'pencil' },
        { es: 'la pluma', en: 'pen', alt: [{ es: 'el bolígrafo', region: 'Spain' }] },
        { es: 'el maestro', en: 'teacher' },
        { es: 'el estudiante', en: 'student' },
        { es: 'la clase', en: 'class' },
        { es: 'la tarea', en: 'homework' },
        { es: 'el examen', en: 'exam' },
        { es: 'la oficina', en: 'office' },
        { es: 'el trabajo', en: 'job' },
        { es: 'el jefe', en: 'boss' },
        { es: 'la reunión', en: 'meeting' },
        { es: 'el correo', en: 'mail' }
      ],
      [
        { es: 'la universidad', en: 'university' },
        { es: 'la carrera', en: 'degree' },
        { es: 'la nota', en: 'grade' },
        { es: 'la pregunta', en: 'question' },
        { es: 'la respuesta', en: 'reply' },
        { es: 'el cuaderno', en: 'notebook' },
        { es: 'la pizarra', en: 'blackboard' },
        { es: 'el horario', en: 'schedule' },
        { es: 'el proyecto', en: 'project' },
        { es: 'la empresa', en: 'company' },
        { es: 'el contrato', en: 'contract' },
        { es: 'el cliente', en: 'customer' },
        { es: 'la entrevista', en: 'interview' },
        { es: 'el informe', en: 'report' },
        { es: 'la fecha', en: 'date' }
      ],
      [
        { es: 'la beca', en: 'scholarship' },
        { es: 'la matrícula', en: 'tuition' },
        { es: 'el título', en: 'diploma' },
        { es: 'la investigación', en: 'research' },
        { es: 'la biblioteca', en: 'library' },
        { es: 'el conocimiento', en: 'knowledge' },
        { es: 'la habilidad', en: 'skill' },
        { es: 'el ascenso', en: 'promotion' },
        { es: 'la jubilación', en: 'retirement' },
        { es: 'el sindicato', en: 'labor union' },
        { es: 'la huelga', en: 'strike' },
        { es: 'el despido', en: 'dismissal' },
        { es: 'la plantilla', en: 'staff' },
        { es: 'el rendimiento', en: 'performance' },
        { es: 'la meta', en: 'goal' }
      ]
    ]
  },
  {
    id: 'ciudad',
    name: 'City & Places',
    emoji: '🏙️',
    stages: [
      [
        { es: 'la tienda', en: 'shop' },
        { es: 'el mercado', en: 'market' },
        { es: 'el parque', en: 'park' },
        { es: 'el banco', en: 'bank' },
        { es: 'la iglesia', en: 'church' },
        { es: 'el hospital', en: 'hospital' },
        { es: 'la plaza', en: 'square' },
        { es: 'el museo', en: 'museum' },
        { es: 'el cine', en: 'cinema' },
        { es: 'el restaurante', en: 'restaurant' },
        { es: 'el edificio', en: 'building' },
        { es: 'la farmacia', en: 'pharmacy' },
        { es: 'el barrio', en: 'neighborhood' },
        { es: 'la esquina', en: 'street corner' },
        { es: 'el centro', en: 'center' }
      ],
      [
        { es: 'la alcaldía', en: 'town hall', alt: [{ es: 'el ayuntamiento', region: 'Spain' }] },
        { es: 'la comisaría', en: 'police station', alt: [{ es: 'la delegación', region: 'Mexico' }] },
        { es: 'el semáforo', en: 'traffic light' },
        { es: 'la acera', en: 'sidewalk', alt: [{ es: 'la banqueta', region: 'Mexico' }, { es: 'la vereda', region: 'South America' }] },
        { es: 'el cruce', en: 'crossroads' },
        { es: 'el estacionamiento', en: 'parking lot', alt: [{ es: 'el aparcamiento', region: 'Spain' }] },
        { es: 'la fuente', en: 'fountain' },
        { es: 'el quiosco', en: 'kiosk' },
        { es: 'la panadería', en: 'bakery' },
        { es: 'la carnicería', en: 'butcher shop' },
        { es: 'la peluquería', en: 'hair salon' },
        { es: 'el supermercado', en: 'supermarket' },
        { es: 'la gasolinera', en: 'gas station' },
        { es: 'el teatro', en: 'theater' },
        { es: 'el estadio', en: 'stadium' }
      ],
      [
        { es: 'el rascacielos', en: 'skyscraper' },
        { es: 'la catedral', en: 'cathedral' },
        { es: 'el cementerio', en: 'cemetery' },
        { es: 'la muralla', en: 'city wall' },
        { es: 'el callejón', en: 'alley' },
        { es: 'la avenida', en: 'avenue' },
        { es: 'el vertedero', en: 'landfill' },
        { es: 'la alcantarilla', en: 'sewer' },
        { es: 'el andamio', en: 'scaffolding' },
        { es: 'la obra', en: 'construction site' },
        { es: 'el suburbio', en: 'suburb' },
        { es: 'las afueras', en: 'outskirts' },
        { es: 'el peatón', en: 'pedestrian' },
        { es: 'la multitud', en: 'crowd' },
        { es: 'el alcalde', en: 'mayor' }
      ]
    ]
  },
  {
    id: 'ropa',
    name: 'Clothing',
    emoji: '👕',
    stages: [
      [
        { es: 'la camisa', en: 'shirt' },
        { es: 'el pantalón', en: 'pants' },
        { es: 'el vestido', en: 'dress' },
        { es: 'la falda', en: 'skirt', alt: [{ es: 'la pollera', region: 'Río de la Plata' }] },
        { es: 'el zapato', en: 'shoe' },
        { es: 'el sombrero', en: 'hat' },
        { es: 'el abrigo', en: 'coat' },
        { es: 'el calcetín', en: 'sock', alt: [{ es: 'la media', region: 'South America' }] },
        { es: 'la chaqueta', en: 'jacket', alt: [{ es: 'la campera', region: 'Río de la Plata' }] },
        { es: 'el cinturón', en: 'belt' },
        { es: 'la bufanda', en: 'scarf' },
        { es: 'el guante', en: 'glove' },
        { es: 'la camiseta', en: 't-shirt' },
        { es: 'la ropa', en: 'clothes' },
        { es: 'la bota', en: 'boot' }
      ],
      [
        { es: 'el bolsillo', en: 'pocket' },
        { es: 'el botón', en: 'button' },
        { es: 'la cremallera', en: 'zipper' },
        { es: 'la manga', en: 'sleeve' },
        { es: 'el collar', en: 'necklace' },
        { es: 'el anillo', en: 'ring' },
        { es: 'el reloj', en: 'watch' },
        { es: 'los lentes', en: 'eyeglasses', alt: [{ es: 'las gafas', region: 'Spain' }, { es: 'los anteojos', region: 'Southern Cone' }] },
        { es: 'el paraguas', en: 'umbrella' },
        { es: 'la cartera', en: 'wallet' },
        { es: 'el bolso', en: 'handbag' },
        { es: 'la corbata', en: 'necktie' },
        { es: 'el pijama', en: 'pajamas' },
        { es: 'el traje', en: 'suit' },
        { es: 'la sandalia', en: 'sandal' }
      ],
      [
        { es: 'el algodón', en: 'cotton' },
        { es: 'la lana', en: 'wool' },
        { es: 'la seda', en: 'silk' },
        { es: 'el cuero', en: 'leather' },
        { es: 'el encaje', en: 'lace' },
        { es: 'la costura', en: 'seam' },
        { es: 'el dobladillo', en: 'hem' },
        { es: 'la percha', en: 'hanger' },
        { es: 'la hebilla', en: 'buckle' },
        { es: 'el tejido', en: 'fabric' },
        { es: 'la prenda', en: 'garment' },
        { es: 'el disfraz', en: 'costume' },
        { es: 'el delantal', en: 'apron' },
        { es: 'la gorra', en: 'cap' },
        { es: 'el chaleco', en: 'vest' }
      ]
    ]
  },
  {
    id: 'emociones',
    name: 'Feelings & Mind',
    emoji: '💭',
    stages: [
      [
        { es: 'el amor', en: 'love' },
        { es: 'el miedo', en: 'fear' },
        { es: 'la alegría', en: 'joy' },
        { es: 'la tristeza', en: 'sadness' },
        { es: 'la rabia', en: 'anger' },
        { es: 'la sorpresa', en: 'surprise' },
        { es: 'el sueño', en: 'dream' },
        { es: 'la idea', en: 'idea' },
        { es: 'la mente', en: 'mind' },
        { es: 'el deseo', en: 'wish' },
        { es: 'la duda', en: 'doubt' },
        { es: 'la esperanza', en: 'hope' },
        { es: 'la memoria', en: 'memory' },
        { es: 'el dolor', en: 'pain' },
        { es: 'la risa', en: 'laughter' }
      ],
      [
        { es: 'los celos', en: 'jealousy' },
        { es: 'la vergüenza', en: 'shame' },
        { es: 'el orgullo', en: 'pride' },
        { es: 'la culpa', en: 'guilt' },
        { es: 'el alivio', en: 'relief' },
        { es: 'la calma', en: 'calmness' },
        { es: 'el enojo', en: 'annoyance', alt: [{ es: 'el enfado', region: 'Spain' }] },
        { es: 'la envidia', en: 'envy' },
        { es: 'la ternura', en: 'tenderness' },
        { es: 'el cariño', en: 'affection' },
        { es: 'la confianza', en: 'trust' },
        { es: 'el respeto', en: 'respect' },
        { es: 'la paciencia', en: 'patience' },
        { es: 'el ánimo', en: 'spirits' },
        { es: 'la soledad', en: 'loneliness' }
      ],
      [
        { es: 'la angustia', en: 'anguish' },
        { es: 'el desprecio', en: 'contempt' },
        { es: 'la nostalgia', en: 'nostalgia' },
        { es: 'el asombro', en: 'astonishment' },
        { es: 'la compasión', en: 'compassion' },
        { es: 'el rencor', en: 'resentment' },
        { es: 'la serenidad', en: 'serenity' },
        { es: 'el entusiasmo', en: 'enthusiasm' },
        { es: 'la melancolía', en: 'melancholy' },
        { es: 'el desánimo', en: 'discouragement' },
        { es: 'la gratitud', en: 'gratitude' },
        { es: 'el remordimiento', en: 'remorse' },
        { es: 'la euforia', en: 'euphoria' },
        { es: 'el recelo', en: 'mistrust' },
        { es: 'la añoranza', en: 'longing' }
      ]
    ]
  },
  {
    id: 'preguntas',
    name: 'Questions & Connectors',
    emoji: '💬',
    stages: [
      [
        { es: 'qué', en: 'what' },
        { es: 'quién', en: 'who' },
        { es: 'cuándo', en: 'when' },
        { es: 'dónde', en: 'where' },
        { es: 'cómo', en: 'how' },
        { es: 'por qué', en: 'why' },
        { es: 'cuál', en: 'which one' },
        { es: 'cuánto', en: 'how much' },
        { es: 'cuántos', en: 'how many' },
        { es: 'y', en: 'and' },
        { es: 'o', en: 'or' },
        { es: 'pero', en: 'but' },
        { es: 'porque', en: 'because' },
        { es: 'también', en: 'also' },
        { es: 'muy', en: 'very' },
        { es: 'más', en: 'more' },
        { es: 'menos', en: 'less' },
        { es: 'sí', en: 'yes' },
        { es: 'aquí', en: 'here' },
        { es: 'allí', en: 'over there' },
        { es: 'ahora', en: 'now' },
        { es: 'siempre', en: 'always' },
        { es: 'nunca', en: 'never' },
        { es: 'tal vez', en: 'maybe' },
        { es: 'por supuesto', en: 'of course' },
        { es: 'así', en: 'like this' },
        { es: 'todo', en: 'everything' },
        { es: 'nada', en: 'nothing' },
        { es: 'alguien', en: 'someone' },
        { es: 'nadie', en: 'no one' }
      ],
      [
        { es: 'aunque', en: 'although' },
        { es: 'entonces', en: 'then' },
        { es: 'además', en: 'besides' },
        { es: 'mientras', en: 'while' },
        { es: 'sin embargo', en: 'however' },
        { es: 'por eso', en: 'that is why' },
        { es: 'es decir', en: 'that is to say' },
        { es: 'sobre todo', en: 'above all' },
        { es: 'en cambio', en: 'on the other hand' },
        { es: 'ya', en: 'already' },
        { es: 'todavía', en: 'still' },
        { es: 'casi', en: 'almost' },
        { es: 'apenas', en: 'barely' },
        { es: 'quizás', en: 'perhaps' },
        { es: 'seguro', en: 'sure' },
        { es: 'cierto', en: 'certain' },
        { es: 'mismo', en: 'same' },
        { es: 'otro', en: 'another' },
        { es: 'cada', en: 'each' },
        { es: 'alguno', en: 'some' },
        { es: 'ninguno', en: 'none' },
        { es: 'ambos', en: 'both' },
        { es: 'varios', en: 'several' },
        { es: 'demasiado', en: 'too much' },
        { es: 'bastante', en: 'quite' },
        { es: 'tanto', en: 'so much' },
        { es: 'según', en: 'according to' },
        { es: 'sin', en: 'without' },
        { es: 'contra', en: 'against' },
        { es: 'hacia', en: 'toward' }
      ],
      [
        { es: 'no obstante', en: 'nevertheless' },
        { es: 'a pesar de', en: 'in spite of' },
        { es: 'siempre que', en: 'whenever' },
        { es: 'a menos que', en: 'unless' },
        { es: 'dado que', en: 'given that' },
        { es: 'puesto que', en: 'seeing as' },
        { es: 'ya que', en: 'since' },
        { es: 'de modo que', en: 'so that' },
        { es: 'por lo tanto', en: 'therefore' },
        { es: 'en resumen', en: 'in summary' },
        { es: 'en fin', en: 'anyway' },
        { es: 'de hecho', en: 'in fact' },
        { es: 'al fin y al cabo', en: 'after all' },
        { es: 'mientras tanto', en: 'meanwhile' },
        { es: 'a la vez', en: 'at the same time' },
        { es: 'en cuanto', en: 'as soon as' },
        { es: 'luego de', en: 'following' },
        { es: 'a través de', en: 'through' },
        { es: 'en lugar de', en: 'instead of' },
        { es: 'junto a', en: 'next to' },
        { es: 'acerca de', en: 'about' },
        { es: 'respecto a', en: 'regarding' },
        { es: 'salvo', en: 'except for' },
        { es: 'incluso', en: 'even' },
        { es: 'más bien', en: 'rather' },
        { es: 'o sea', en: 'in other words' },
        { es: 'por si acaso', en: 'just in case' },
        { es: 'a lo mejor', en: 'possibly' },
        { es: 'de repente', en: 'suddenly' },
        { es: 'por fin', en: 'at last' }
      ]
    ]
  },
  {
    id: 'lugar',
    name: 'Where Things Are',
    emoji: '🧭',
    stages: [
      [
        { es: 'encima', en: 'on top' },
        { es: 'debajo', en: 'underneath' },
        { es: 'delante', en: 'in front' },
        { es: 'detrás', en: 'behind' },
        { es: 'dentro', en: 'inside' },
        { es: 'afuera', en: 'outside' },
        { es: 'cerca', en: 'nearby' },
        { es: 'lejos', en: 'far' },
        { es: 'entre', en: 'between' },
        { es: 'al lado', en: 'beside' },
        { es: 'arriba', en: 'up' },
        { es: 'abajo', en: 'down' },
        { es: 'adelante', en: 'forward' },
        { es: 'la derecha', en: 'the right' },
        { es: 'la izquierda', en: 'the left' },
        { es: 'recto', en: 'straight ahead' },
        { es: 'el lado', en: 'the side' },
        { es: 'el frente', en: 'the front' },
        { es: 'alrededor', en: 'around' },
        { es: 'sobre', en: 'over' },
        { es: 'hasta', en: 'until' },
        { es: 'desde', en: 'from' },
        { es: 'el norte', en: 'north' },
        { es: 'el sur', en: 'south' },
        { es: 'el este', en: 'east' },
        { es: 'el oeste', en: 'west' },
        { es: 'el camino', en: 'the path' },
        { es: 'la dirección', en: 'the address' },
        { es: 'el rincón', en: 'the inside corner' },
        { es: 'la vuelta', en: 'the turn' }
      ],
      [
        { es: 'subir', en: 'to go up' },
        { es: 'bajar', en: 'to go down' },
        { es: 'entrar', en: 'to go in' },
        { es: 'cruzar', en: 'to cross' },
        { es: 'doblar', en: 'to turn' },
        { es: 'seguir', en: 'to keep going' },
        { es: 'parar', en: 'to stop' },
        { es: 'regresar', en: 'to head back' },
        { es: 'acercarse', en: 'to approach' },
        { es: 'alejarse', en: 'to move away' },
        { es: 'mover', en: 'to move' },
        { es: 'colocar', en: 'to place' },
        { es: 'quedarse', en: 'to stay' },
        { es: 'caber', en: 'to fit' },
        { es: 'señalar', en: 'to point out' },
        { es: 'ubicar', en: 'to locate' },
        { es: 'el piso', en: 'the floor' },
        { es: 'la planta', en: 'the story' },
        { es: 'el borde', en: 'the edge' },
        { es: 'la orilla', en: 'the shore' },
        { es: 'el centro comercial', en: 'the mall' },
        { es: 'la ruta', en: 'the route' },
        { es: 'el atajo', en: 'the shortcut' },
        { es: 'la distancia', en: 'the distance' },
        { es: 'el kilómetro', en: 'the kilometer' },
        { es: 'la altura', en: 'the height' },
        { es: 'la profundidad', en: 'the depth' },
        { es: 'el sentido', en: 'the direction of travel' },
        { es: 'la ubicación', en: 'the location' },
        { es: 'el punto', en: 'the point' }
      ],
      [
        { es: 'rodear', en: 'to surround' },
        { es: 'atravesar', en: 'to go across' },
        { es: 'sobresalir', en: 'to stick out' },
        { es: 'apartarse', en: 'to step aside' },
        { es: 'desviarse', en: 'to veer off' },
        { es: 'retroceder', en: 'to back up' },
        { es: 'avanzar', en: 'to advance' },
        { es: 'descender', en: 'to descend' },
        { es: 'ascender', en: 'to ascend' },
        { es: 'bordear', en: 'to skirt' },
        { es: 'el trayecto', en: 'the journey leg' },
        { es: 'el desnivel', en: 'the drop' },
        { es: 'la ladera', en: 'the hillside' },
        { es: 'la cima', en: 'the summit' },
        { es: 'el llano', en: 'the plain' },
        { es: 'el cruce de caminos', en: 'the crossroads' },
        { es: 'la bifurcación', en: 'the fork' },
        { es: 'el punto de partida', en: 'the starting point' },
        { es: 'el destino final', en: 'the final destination' },
        { es: 'la señalización', en: 'the signage' },
        { es: 'el perímetro', en: 'the perimeter' },
        { es: 'el eje', en: 'the axis' },
        { es: 'la franja', en: 'the strip' },
        { es: 'el tramo', en: 'the stretch' },
        { es: 'la vertiente', en: 'the slope' },
        { es: 'el paraje', en: 'the spot' },
        { es: 'la lindera', en: 'the boundary' },
        { es: 'el recodo', en: 'the bend' },
        { es: 'la explanada', en: 'the esplanade' },
        { es: 'el mirador', en: 'the lookout' }
      ]
    ]
  },
  {
    id: 'rutina',
    name: 'Daily Routine',
    emoji: '⏰',
    stages: [
      [
        { es: 'despertarse', en: 'to wake up' },
        { es: 'levantarse', en: 'to get up' },
        { es: 'ducharse', en: 'to shower' },
        { es: 'bañarse', en: 'to bathe' },
        { es: 'vestirse', en: 'to get dressed' },
        { es: 'peinarse', en: 'to comb your hair' },
        { es: 'cepillarse', en: 'to brush' },
        { es: 'lavarse', en: 'to wash up' },
        { es: 'afeitarse', en: 'to shave' },
        { es: 'desayunar', en: 'to have breakfast' },
        { es: 'almorzar', en: 'to have lunch' },
        { es: 'cenar', en: 'to have dinner' },
        { es: 'acostarse', en: 'to go to bed' },
        { es: 'dormirse', en: 'to fall asleep' },
        { es: 'descansar', en: 'to rest' },
        { es: 'la mañana', en: 'the morning' },
        { es: 'la noche', en: 'the night' },
        { es: 'temprano', en: 'early' },
        { es: 'el despertador', en: 'the alarm clock' },
        { es: 'el cepillo', en: 'the brush' },
        { es: 'la pasta de dientes', en: 'the toothpaste' },
        { es: 'el champú', en: 'the shampoo' },
        { es: 'la rutina', en: 'the routine' },
        { es: 'la siesta', en: 'the nap' },
        { es: 'listo', en: 'ready' },
        { es: 'ocupado', en: 'busy' },
        { es: 'cansado', en: 'tired' },
        { es: 'la ducha', en: 'the shower' },
        { es: 'la almohada de viaje', en: 'the travel pillow' },
        { es: 'la bata', en: 'the robe' }
      ],
      [
        { es: 'maquillarse', en: 'to put on makeup' },
        { es: 'secarse', en: 'to dry off' },
        { es: 'apurarse', en: 'to hurry' },
        { es: 'alistarse', en: 'to get ready' },
        { es: 'acomodarse', en: 'to settle in' },
        { es: 'estirarse', en: 'to stretch' },
        { es: 'bostezar', en: 'to yawn' },
        { es: 'madrugar', en: 'to rise early' },
        { es: 'trasnochar', en: 'to stay up late' },
        { es: 'la costumbre', en: 'the habit' },
        { es: 'el calendario', en: 'the calendar' },
        { es: 'la agenda', en: 'the planner' },
        { es: 'el pendiente', en: 'the errand' },
        { es: 'la tarea diaria', en: 'the daily chore' },
        { es: 'el quehacer', en: 'the household task' },
        { es: 'barrer', en: 'to sweep' },
        { es: 'trapear', en: 'to mop' },
        { es: 'planchar', en: 'to iron' },
        { es: 'doblar la ropa', en: 'to fold the laundry' },
        { es: 'tender', en: 'to hang out' },
        { es: 'regar', en: 'to water' },
        { es: 'sacar la basura', en: 'to take out the trash' },
        { es: 'lavar los platos', en: 'to do the dishes' },
        { es: 'tender la cama', en: 'to make the bed' },
        { es: 'el detergente', en: 'the detergent' },
        { es: 'la escoba', en: 'the broom' },
        { es: 'el trapo', en: 'the rag' },
        { es: 'el balde', en: 'the bucket' },
        { es: 'la aspiradora', en: 'the vacuum' },
        { es: 'el orden', en: 'the tidiness' }
      ],
      [
        { es: 'desvelarse', en: 'to lose sleep' },
        { es: 'acurrucarse', en: 'to curl up' },
        { es: 'remolonear', en: 'to laze about' },
        { es: 'desperezarse', en: 'to shake off sleep' },
        { es: 'arreglarse', en: 'to smarten up' },
        { es: 'encargarse', en: 'to take charge of' },
        { es: 'posponer', en: 'to postpone' },
        { es: 'cumplir', en: 'to carry out' },
        { es: 'el trajín', en: 'the daily grind' },
        { es: 'la faena', en: 'the chore round' },
        { es: 'el sosiego', en: 'the calm' },
        { es: 'el ajetreo', en: 'the bustle' },
        { es: 'la pauta', en: 'the pattern' },
        { es: 'el ritmo', en: 'the rhythm' },
        { es: 'la disciplina', en: 'the discipline' },
        { es: 'el hábito', en: 'the ingrained habit' },
        { es: 'la constancia', en: 'the perseverance' },
        { es: 'el descuido', en: 'the oversight' },
        { es: 'la pereza', en: 'the laziness' },
        { es: 'el madrugón', en: 'the early start' },
        { es: 'la trasnochada', en: 'the late night' },
        { es: 'el aseo', en: 'the washing up' },
        { es: 'la higiene', en: 'the hygiene' },
        { es: 'el arreglo', en: 'the touch-up' },
        { es: 'la limpieza', en: 'the cleaning' },
        { es: 'el desorden', en: 'the mess' },
        { es: 'la rutina diaria', en: 'the daily round' },
        { es: 'el descanso', en: 'the break' },
        { es: 'la jornada', en: 'the working day' },
        { es: 'el ocio', en: 'the leisure' }
      ]
    ]
  },
  {
    id: 'salud',
    name: 'Health & the Doctor',
    emoji: '🩺',
    stages: [
      [
        { es: 'la salud', en: 'health' },
        { es: 'el médico', en: 'the physician' },
        { es: 'la enfermera', en: 'the nurse' },
        { es: 'la cita', en: 'the appointment' },
        { es: 'la pastilla', en: 'the pill' },
        { es: 'la medicina', en: 'the medicine' },
        { es: 'la fiebre', en: 'the fever' },
        { es: 'la tos', en: 'the cough' },
        { es: 'el resfriado', en: 'the head cold' },
        { es: 'la gripe', en: 'the flu' },
        { es: 'doler', en: 'to ache' },
        { es: 'enfermo', en: 'sick' },
        { es: 'sano', en: 'healthy' },
        { es: 'la herida', en: 'the wound' },
        { es: 'la venda', en: 'the bandage' },
        { es: 'la vacuna', en: 'the vaccine' },
        { es: 'la inyección', en: 'the shot' },
        { es: 'el consultorio', en: 'the clinic' },
        { es: 'la ambulancia', en: 'the ambulance' },
        { es: 'el jarabe', en: 'the syrup' },
        { es: 'la curita', en: 'the adhesive bandage' },
        { es: 'el termómetro', en: 'the thermometer' },
        { es: 'el peso', en: 'the weight' },
        { es: 'la estatura', en: 'the standing height' },
        { es: 'respirar', en: 'to breathe' },
        { es: 'toser', en: 'to cough' },
        { es: 'estornudar', en: 'to sneeze' },
        { es: 'vomitar', en: 'to throw up' },
        { es: 'mejorarse', en: 'to get better' },
        { es: 'el paciente', en: 'the patient' }
      ],
      [
        { es: 'el síntoma', en: 'the symptom' },
        { es: 'el diagnóstico', en: 'the diagnosis' },
        { es: 'el tratamiento', en: 'the treatment' },
        { es: 'la dosis', en: 'the dose' },
        { es: 'la alergia', en: 'the allergy' },
        { es: 'el mareo', en: 'the dizziness' },
        { es: 'la náusea', en: 'the nausea' },
        { es: 'el escalofrío', en: 'the chill' },
        { es: 'la infección', en: 'the infection' },
        { es: 'la lesión', en: 'the injury' },
        { es: 'el moretón', en: 'the bruise' },
        { es: 'la cicatriz', en: 'the scar' },
        { es: 'la radiografía', en: 'the x-ray' },
        { es: 'la sala de espera', en: 'the waiting room' },
        { es: 'la urgencia', en: 'the emergency' },
        { es: 'el seguro médico', en: 'the health insurance' },
        { es: 'la cirugía', en: 'the surgery' },
        { es: 'el cirujano', en: 'the surgeon' },
        { es: 'el dentista', en: 'the dentist' },
        { es: 'la muela', en: 'the molar' },
        { es: 'la vista', en: 'the eyesight' },
        { es: 'los lentes de contacto', en: 'the contact lenses' },
        { es: 'el yeso', en: 'the cast' },
        { es: 'la muleta', en: 'the crutch' },
        { es: 'la silla de ruedas', en: 'the wheelchair' },
        { es: 'recetar', en: 'to prescribe' },
        { es: 'curar', en: 'to cure' },
        { es: 'sanar', en: 'to heal' },
        { es: 'prevenir', en: 'to prevent' },
        { es: 'el chequeo', en: 'the checkup' }
      ],
      [
        { es: 'el padecimiento', en: 'the ailment' },
        { es: 'la dolencia', en: 'the complaint' },
        { es: 'el malestar', en: 'the discomfort' },
        { es: 'la recaída', en: 'the relapse' },
        { es: 'la secuela', en: 'the aftereffect' },
        { es: 'el contagio', en: 'the contagion' },
        { es: 'la epidemia', en: 'the epidemic' },
        { es: 'el brote', en: 'the outbreak' },
        { es: 'la cepa', en: 'the strain' },
        { es: 'el sistema inmune', en: 'the immune system' },
        { es: 'la presión arterial', en: 'the blood pressure' },
        { es: 'el pulso', en: 'the pulse' },
        { es: 'el latido', en: 'the heartbeat' },
        { es: 'la respiración', en: 'the breathing' },
        { es: 'la cicatrización', en: 'the healing over' },
        { es: 'el reposo', en: 'the bed rest' },
        { es: 'la rehabilitación', en: 'the rehabilitation' },
        { es: 'la terapia', en: 'the therapy' },
        { es: 'el especialista', en: 'the specialist' },
        { es: 'la consulta', en: 'the consultation' },
        { es: 'el expediente', en: 'the medical record' },
        { es: 'el ayuno', en: 'the fast' },
        { es: 'la dieta', en: 'the diet' },
        { es: 'el bienestar', en: 'the wellbeing' },
        { es: 'la fatiga', en: 'the fatigue' },
        { es: 'el insomnio', en: 'the insomnia' },
        { es: 'la ansiedad', en: 'the anxiousness' },
        { es: 'el estrés', en: 'the stress' },
        { es: 'la recuperación', en: 'the recovery' },
        { es: 'el alivio médico', en: 'the medical relief' }
      ]
    ]
  },
  {
    id: 'tecnologia',
    name: 'Technology & Online',
    emoji: '💻',
    stages: [
      [
        { es: 'la computadora', en: 'the computer' },
        { es: 'el celular', en: 'the cell phone' },
        { es: 'la pantalla', en: 'the screen' },
        { es: 'el teclado', en: 'the keyboard' },
        { es: 'la contraseña', en: 'the password' },
        { es: 'el correo electrónico', en: 'the email' },
        { es: 'la aplicación', en: 'the app' },
        { es: 'el archivo', en: 'the file' },
        { es: 'la carpeta', en: 'the folder' },
        { es: 'la red', en: 'the network' },
        { es: 'el enlace', en: 'the link' },
        { es: 'descargar', en: 'to download' },
        { es: 'guardar', en: 'to save' },
        { es: 'borrar', en: 'to delete' },
        { es: 'la batería', en: 'the battery' },
        { es: 'cargar', en: 'to charge' },
        { es: 'el cargador', en: 'the charger' },
        { es: 'la señal', en: 'the signal' },
        { es: 'el mensaje', en: 'the message' },
        { es: 'la llamada', en: 'the call' },
        { es: 'el usuario', en: 'the username' },
        { es: 'la página', en: 'the page' },
        { es: 'imprimir', en: 'to print' },
        { es: 'la impresora', en: 'the printer' },
        { es: 'los audífonos', en: 'the headphones' },
        { es: 'el altavoz', en: 'the loudspeaker' },
        { es: 'la cámara', en: 'the camera' },
        { es: 'la foto', en: 'the photo' },
        { es: 'el video', en: 'the video' },
        { es: 'el sitio web', en: 'the website' }
      ],
      [
        { es: 'el navegador', en: 'the browser' },
        { es: 'el buscador', en: 'the search engine' },
        { es: 'la nube digital', en: 'the cloud' },
        { es: 'la copia de seguridad', en: 'the backup' },
        { es: 'la actualización', en: 'the update' },
        { es: 'el programa', en: 'the software program' },
        { es: 'el dispositivo', en: 'the device' },
        { es: 'la tableta', en: 'the tablet' },
        { es: 'el disco duro', en: 'the hard drive' },
        { es: 'la memoria RAM', en: 'the working memory' },
        { es: 'el archivo adjunto', en: 'the attachment' },
        { es: 'la bandeja de entrada', en: 'the inbox' },
        { es: 'el correo basura', en: 'the spam' },
        { es: 'la publicación', en: 'the post' },
        { es: 'el seguidor', en: 'the follower' },
        { es: 'la pantalla táctil', en: 'the touchscreen' },
        { es: 'el enrutador', en: 'the router' },
        { es: 'la conexión', en: 'the connection' },
        { es: 'el ajuste', en: 'the setting' },
        { es: 'la notificación', en: 'the notification' },
        { es: 'el respaldo', en: 'the safeguard' },
        { es: 'compartir', en: 'to share' },
        { es: 'subir un archivo', en: 'to upload' },
        { es: 'escanear', en: 'to scan' },
        { es: 'reiniciar', en: 'to restart' },
        { es: 'actualizar', en: 'to refresh' },
        { es: 'instalar', en: 'to install' },
        { es: 'desinstalar', en: 'to uninstall' },
        { es: 'conectarse', en: 'to log on' },
        { es: 'desconectarse', en: 'to log off' }
      ],
      [
        { es: 'el algoritmo', en: 'the algorithm' },
        { es: 'el servidor', en: 'the server' },
        { es: 'la base de datos', en: 'the database' },
        { es: 'el cifrado', en: 'the encryption' },
        { es: 'la brecha', en: 'the breach' },
        { es: 'el cortafuegos', en: 'the firewall' },
        { es: 'el respaldo automático', en: 'the automatic backup' },
        { es: 'la interfaz', en: 'the interface' },
        { es: 'el código fuente', en: 'the source code' },
        { es: 'la depuración', en: 'the debugging' },
        { es: 'el ancho de banda', en: 'the bandwidth' },
        { es: 'la latencia', en: 'the latency' },
        { es: 'el almacenamiento', en: 'the storage' },
        { es: 'la nube privada', en: 'the private cloud' },
        { es: 'el respaldo remoto', en: 'the remote backup' },
        { es: 'la inteligencia artificial', en: 'the artificial intelligence' },
        { es: 'el aprendizaje automático', en: 'the machine learning' },
        { es: 'el modelo', en: 'the model' },
        { es: 'el entrenamiento', en: 'the training run' },
        { es: 'la privacidad', en: 'the privacy' },
        { es: 'el rastreo', en: 'the tracking' },
        { es: 'la huella digital', en: 'the digital fingerprint' },
        { es: 'el respaldo en línea', en: 'the online backup' },
        { es: 'la vulnerabilidad', en: 'the vulnerability' },
        { es: 'el parche', en: 'the patch' },
        { es: 'la licencia', en: 'the license' },
        { es: 'el código abierto', en: 'the open source' },
        { es: 'la suscripción', en: 'the subscription' },
        { es: 'el soporte técnico', en: 'the tech support' },
        { es: 'la obsolescencia', en: 'the obsolescence' }
      ]
    ]
  },
  {
    id: 'naturaleza',
    name: 'Nature & Outdoors',
    emoji: '🏔️',
    stages: [
      [
        { es: 'el río', en: 'the river' },
        { es: 'la montaña', en: 'the mountain' },
        { es: 'el bosque', en: 'the forest' },
        { es: 'el mar', en: 'the sea' },
        { es: 'el lago', en: 'the lake' },
        { es: 'el árbol', en: 'the tree' },
        { es: 'la flor', en: 'the flower' },
        { es: 'la hoja', en: 'the leaf' },
        { es: 'la rama', en: 'the branch' },
        { es: 'la raíz', en: 'the root' },
        { es: 'la piedra', en: 'the stone' },
        { es: 'la arena', en: 'the sand' },
        { es: 'la ola', en: 'the wave' },
        { es: 'la tierra', en: 'the soil' },
        { es: 'el campo', en: 'the countryside' },
        { es: 'la colina', en: 'the hill' },
        { es: 'el valle', en: 'the valley' },
        { es: 'la cueva', en: 'the cave' },
        { es: 'el desierto', en: 'the desert' },
        { es: 'la selva', en: 'the jungle' },
        { es: 'el volcán', en: 'the volcano' },
        { es: 'la costa', en: 'the coast' },
        { es: 'el pasto', en: 'the grass' },
        { es: 'la semilla', en: 'the seed' },
        { es: 'el tronco', en: 'the trunk' },
        { es: 'la cascada', en: 'the waterfall' },
        { es: 'el arroyo', en: 'the creek' },
        { es: 'la roca', en: 'the boulder' },
        { es: 'el barro', en: 'the mud' },
        { es: 'el polvo', en: 'the dust' }
      ],
      [
        { es: 'el panorama', en: 'the vista' },
        { es: 'el amanecer natural', en: 'the daybreak' },
        { es: 'el horizonte', en: 'the horizon' },
        { es: 'la marea', en: 'the tide' },
        { es: 'la corriente', en: 'the current' },
        { es: 'el acantilado', en: 'the cliff' },
        { es: 'la bahía', en: 'the bay' },
        { es: 'el pantano', en: 'the swamp' },
        { es: 'la laguna', en: 'the lagoon' },
        { es: 'el manantial', en: 'the spring' },
        { es: 'la pradera', en: 'the meadow' },
        { es: 'el matorral', en: 'the scrub' },
        { es: 'la maleza', en: 'the weeds' },
        { es: 'el helecho', en: 'the fern' },
        { es: 'el musgo', en: 'the moss' },
        { es: 'la corteza', en: 'the bark' },
        { es: 'el capullo', en: 'the bud' },
        { es: 'el pétalo', en: 'the petal' },
        { es: 'el polen', en: 'the pollen' },
        { es: 'la savia', en: 'the sap' },
        { es: 'el nido', en: 'the nest' },
        { es: 'la madriguera', en: 'the burrow' },
        { es: 'la huella', en: 'the animal track' },
        { es: 'el rebaño', en: 'the herd' },
        { es: 'la bandada', en: 'the flock' },
        { es: 'el enjambre', en: 'the swarm' },
        { es: 'sembrar', en: 'to sow' },
        { es: 'cosechar', en: 'to harvest' },
        { es: 'podar', en: 'to prune' },
        { es: 'talar', en: 'to fell' }
      ],
      [
        { es: 'el ecosistema', en: 'the ecosystem' },
        { es: 'la biodiversidad', en: 'the biodiversity' },
        { es: 'el hábitat', en: 'the habitat' },
        { es: 'la especie', en: 'the species' },
        { es: 'la cadena alimenticia', en: 'the food chain' },
        { es: 'el depredador', en: 'the predator' },
        { es: 'la presa', en: 'the prey' },
        { es: 'la migración', en: 'the migration' },
        { es: 'la hibernación', en: 'the hibernation' },
        { es: 'el clima templado', en: 'the temperate climate' },
        { es: 'la sequía prolongada', en: 'the drought' },
        { es: 'la erosión', en: 'the erosion' },
        { es: 'el deshielo', en: 'the thaw' },
        { es: 'la cordillera', en: 'the mountain range' },
        { es: 'el estuario', en: 'the estuary' },
        { es: 'el afluente', en: 'the tributary' },
        { es: 'la cuenca', en: 'the basin' },
        { es: 'el yacimiento', en: 'the deposit' },
        { es: 'el mineral', en: 'the mineral' },
        { es: 'la caliza', en: 'the limestone' },
        { es: 'el sedimento', en: 'the sediment' },
        { es: 'la ladera boscosa', en: 'the wooded slope' },
        { es: 'el dosel', en: 'the canopy' },
        { es: 'la reforestación', en: 'the reforestation' },
        { es: 'la tala', en: 'the logging' },
        { es: 'la conservación', en: 'the conservation' },
        { es: 'el guardabosques', en: 'the ranger' },
        { es: 'la reserva natural', en: 'the nature reserve' },
        { es: 'el sendero ecológico', en: 'the nature trail' },
        { es: 'la huella ecológica', en: 'the ecological footprint' }
      ]
    ]
  }
];

/** Stable identity for a word, used as the progress-map key. */
export function wordId(word) {
  return word.es;
}

export function getDeck(deckId) {
  return DECKS.find((deck) => deck.id === deckId) ?? null;
}

/** Words in one stage of one deck. `stage` is zero-based. */
export function stageWords(deckId, stage) {
  if (deckId === ALL_DECK_ID) return DECKS.flatMap((deck) => deck.stages[stage] ?? []);
  return getDeck(deckId)?.stages[stage] ?? [];
}

/** Every word in a deck, across all stages. */
export function deckWords(deckId) {
  if (deckId === ALL_DECK_ID) return DECKS.flatMap((deck) => deck.stages.flat());
  return getDeck(deckId)?.stages.flat() ?? [];
}
